CREATE TABLE Ofertas (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    IdTarea UNIQUEIDENTIFIER NOT NULL,
    IdCreadorOferta UNIQUEIDENTIFIER NOT NULL,
    MensajeOferta NVARCHAR(MAX) NOT NULL,
    FechaCreacion DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (IdTarea) REFERENCES Tareas(Id),
    FOREIGN KEY (IdCreadorOferta) REFERENCES Users(Id)
);