CREATE TABLE Users (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Email NVARCHAR(255) UNIQUE NOT NULL,
    PasswordHash NVARCHAR(255) NOT NULL,
    Salt NVARCHAR(255) NOT NULL,
    Nombre NVARCHAR(255) NOT NULL,
    Apellido NVARCHAR(255) NOT NULL,
    ProfilePictureUrl NVARCHAR(500) NULL, -- URL de la imagen de perfil
    isGoogleUser BIT NOT NULL DEFAULT 0,
    googleUserId NVARCHAR(255) NULL,
    Role NVARCHAR(50) NOT NULL DEFAULT 'User',
    CreatedAt DATETIME NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME NULL
);

CREATE TABLE UserTokens (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    Token NVARCHAR(255) NOT NULL UNIQUE,
    Expiration DATETIME NOT NULL DEFAULT DATEADD(DAY, 30, GETDATE()),
    CreatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

--DROP table Ofertas
--drop table Tareas
--drop table UserTokens
--DROP TABLE Users

select * from users
select * from Tareas